feat(bspwm): add checks for dependencies

diff --git a/wm/bspwm/bspwmrc b/wm/bspwm/bspwmrc
--- a/wm/bspwm/bspwmrc
+++ b/wm/bspwm/bspwmrc
@@ -1,5 +1,15 @@
 #! /bin/sh
 
+function _is_callable {
+  command -v "$1" >/dev/null || return 1
+}
+
+if ! _is_callable sxhkd ; then
+  echo "sxhkd not found : exiting"
+  bspc quit
+  exit
+fi
+
 # Defaults: look them up!
 pgrep -x sxhkd > /dev/null || sxhkd &
 
@@ -20,10 +30,16 @@ bspc rule -a Screenkey manage=off
 
 # Mine
 # Background
-feh --bg-scale ~/Pictures/wallpapers/firewatch-orange-blue.png
+if _is_callable feh ; then
+  feh --bg-scale ~/Pictures/wallpapers/firewatch-orange-blue.png
+fi
 
 # Polybar
-$HOME/.config/polybar/launch.sh
+if _is_callable polybar ; then
+  $HOME/.config/polybar/launch.sh
+fi
 
 # Remapping caps lock
-[ -f $HOME/.config/arch/remap-caps-lock.sh ] && $HOME/.config/arch/remap-caps-lock.sh
+if _is_callable xcape ; then
+  [ -f $HOME/.config/arch/remap-caps-lock.sh ] && $HOME/.config/arch/remap-caps-lock.sh
+fi
